---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  vars:
    grafana_pass: grafana#@!

  pre_tasks:
    - name: If missing, install Python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

    - name: Install packages
      ansible.builtin.package:
        name: acl
        state: present


  roles:
    - role: loki_driver
    - role: geerlingguy.docker
      vars:
        docker_compose_version: "v2.11.1"
        docker_daemon_options:
          log-driver: loki
          log-opts:
            loki-url: http://{{ ansible_default_ipv4.address }}:3100/loki/api/v1/push
            mode: non-blocking

    - role: geerlingguy.node_exporter
      vars:
        node_exporter_version: "1.6.1"
    - role: grafana_compose
      vars:
        gc_alermanager_version: "v0.26.0"
        gc_loki_version: "2.9.0"
        gc_promtail_version: "2.9.0"
        gc_prometheus_version: "v2.47.0"
        gc_cadvisor_version: "v0.47.2"
        gc_grafana_version: "10.0.5"
        gc_enable_acme_proxy: false
        gc_service_manage: true
        gc_loki_bind_addresses: ["0.0.0.0"]
        gc_prometheus_bind_addresses: ["0.0.0.0"]
        gc_grafana_bind_addresses: ["0.0.0.0"]
        gc_grafana_password: "{{ grafana_pass }}"
        gc_cadvisor_exporters: ["cadvisor:8080"]
        gc_node_exporters: ["{{ ansible_default_ipv4.address }}:9100"]
    - role: grafana_manage
