---
- name: Check if /usr/bin/docker exists
  stat:
    path: /usr/bin/docker
  register: docker_file_info

- name: Update APT cache
  apt:
    update_cache: yes
  when: docker_file_info.stat.exists == false

- name: Install Docker if it doesn't exist
  ansible.builtin.package:
    name: docker.io
    state: present
  when: docker_file_info.stat.exists == false

- name: Install Loki Docker Driver
  community.docker.docker_plugin:
    plugin_name: grafana/loki-docker-driver:latest
    alias: loki
    state: enable
