---
- name: Wait until Grafana HTTP status is 200
  ansible.builtin.uri:
    url: http://{{ ansible_default_ipv4.address }}:3000
    return_content: true
    validate_certs: false
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 6
  delay: 10
  register: uri_output

- name: Import node exporter dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://{{ ansible_default_ipv4.address }}:3000
    grafana_user: grafana_admin
    grafana_password: "{{ grafana_pass }}"
    dashboard_url: https://grafana.com/api/dashboards/1860/revisions/32/download

- name: Add USE dashboard file
  ansible.builtin.copy:
    src: use_dashboard.json
    dest: /tmp/use_dashboard.json
    mode: '0644'

- name: Import USE dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://{{ ansible_default_ipv4.address }}:3000
    grafana_user: grafana_admin
    grafana_password: "{{ grafana_pass }}"
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: /tmp/use_dashboard.json
