---
gc_base_directory_sanitized: '{{ gc_base_directory | regex_replace("\/$", "") }}'
gc_loki_bind_mount_dir_sanitized: '{{ gc_loki_bind_mount_dir | regex_replace("\/$", "") }}'
gc_prometheus_bind_mount_dir_sanitized: '{{ gc_prometheus_bind_mount_dir | regex_replace("\/$", "") }}'
gc_grafana_bind_mount_dir_sanitized: '{{ gc_grafana_bind_mount_dir | regex_replace("\/$", "") }}'
gc_nginx_log_bind_mount_dir_sanitized: '{{ gc_nginx_log_bind_mount_dir | regex_replace("\/$", "") }}'
gc_docker_bin_dir_sanitized: '{{ gc_docker_bin_dir | regex_replace("\/$", "") }}'
gc_compose_command: '{{ "docker compose" if gc_compose_major_version == 2 else "docker-compose" }}'
