- name: Converge
  hosts: all
  gather_facts: true
  become: true

  vars:
    roles_to_include:
      - alertmanager
      - grafana
      - cadvisor
      - prometheus
      - loki
      - node_exporter

  roles:
    - geerlingguy.docker

  tasks:
    - name: If missing, install Python3
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

    - name: Include additional roles dynamically
      include_role:
        name: "{{ item }}"
      loop: "{{ roles_to_include }}"
