- name: Converge
  hosts: all
  gather_facts: true
  become: true

  vars:
    roles_to_include:
      - cadvisor

  roles:
    - role: geerlingguy.docker
    - role: dominiquefuchs.grafana_compose
      vars:
        gc_enable_acme_proxy: false
        gc_service_manage: true
        gc_loki_bind_addresses: ['0.0.0.0']
        gc_prometheus_bind_addresses: ['0.0.0.0']
        gc_grafana_bind_addresses: ['0.0.0.0']
        gc_grafana_password: mygrafanapass

  pre_tasks:
    - name: If missing, install Python3
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3 acl)
      changed_when: false

    - name: Install packages
      package:
        name: acl
        state: present


