---
driver:
  name: vagrant
  provider:
    name: VBox

platforms:
  - name: vagrant-ubuntu
    box: generic/ubuntu2004
    memory: 2048
    cpus: 4
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 9090, host: 9090"
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles:~/.ansible/roles
