---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04  # Use an appropriate base image
    privileged: true
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: ansible
