---
driver:
  name: vagrant
  provider:
    name: VBox

platforms:
  - name: vagrant-ubuntu
    box: generic/ubuntu2004
    memory: 2048
    cpus: 4

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles:~/.ansible/roles
