---
driver:
  name: vagrant
  provider:
    name: VBox

platforms:
  - name: vagrant-ubuntu
    box: generic/ubuntu2004
    memory: 2048
    cpus: 4
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
      - network_name: forwarded_port
        guest: 3000
        host: 3000
      - network_name: forwarded_port
        guest: 3100
        host: 3100
      - network_name: forwarded_port
        guest: 9090
        host: 9090
      - network_name: forwarded_port
        guest: 9093
        host: 9093

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles:~/.ansible/roles
