---
- name: Install monitoring stack
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add APT repositories
      apt_repository:
        repo: "{{ item.repo }}"
        state: present
      loop:
        - { repo: 'deb https://packages.grafana.com/oss/deb stable main', state: 'present', filename: 'grafana' }
        - { repo: 'deb https://packages.prometheus.io/apt/prometheus/ bionic main', state: 'present', filename: 'prometheus' }
        - { repo: 'deb https://packages.prometheus.io/apt/alertmanager/ bionic main', state: 'present', filename: 'alertmanager' }
        - { repo: 'deb https://packages.grafana.com/loki/deb stable main', state: 'present', filename: 'loki' }

    - name: Import Grafana GPG key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Install required packages
      apt:
        name:
          - grafana
          - prometheus
          - alertmanager
          - loki
          - promtail
        state: present

    - name: Start and enable services
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - grafana-server
        - prometheus
        - alertmanager
        - loki
        - promtail
